[versions]
# ANDROID
agp = "8.13.0"
compileSdk = "36"
minSdk = "24"
targetSdk = "36"

# ANDROIDX
androidx-appcompat = "1.7.1"
androidx-core = "1.17.0"
androidx-lifecycle = "2.9.5"
androidx-material = "1.13.0"
androidx-splashscreen = "1.0.1"

# COIL
coil = "3.3.0"

# COMPOSE MULTIPLATFORM
compose-multiplatform = "1.9.2"

# DATA STORE
data-store = "1.1.7"

# DETEKT
detekt = "1.23.8"

# FIREBASE
firebase-crashlytics = "3.0.6"
firebase-kmp = "2.4.0"

# GOOGLE
google-services = "4.4.4"

# KOIN
koin = "4.1.1"

# KOTLIN
kotlin = "2.2.21"

# KOTLINX
kotlinx-coroutines = "1.10.2"
kotlinx-dateTime = "0.7.1"
kotlinx-immutableCollections = "0.4.0"

# KSP
ksp = "2.2.10-2.0.2"

# KTOR
ktor = "3.3.1"

# NAVIGATION
navigation-compose = "2.9.1"

# OKIO
okio = "3.16.2"

# SQLITE
sqlite = "2.6.1"

# ROOM
room = "2.8.3"

# TEST
androidx-espresso = "3.7.0"
androidx-testExt = "1.3.0"
junit = "4.13.2"

[libraries]
# ANDROIDX
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-splashscreen" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "androidx-material" }

# COIL
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network-ktor = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }

# DATA STORE
data-store = { module = "androidx.datastore:datastore", version.ref = "data-store" }
data-store-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "data-store" }

# DETEKT
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

# FIREBASE
firebase-analytics-kmp = { module = "dev.gitlive:firebase-analytics", version.ref = "firebase-kmp"}
firebase-app-kmp = { module = "dev.gitlive:firebase-app", version.ref = "firebase-kmp"}
firebase-auth-kmp = { module = "dev.gitlive:firebase-auth", version.ref = "firebase-kmp"}
firebase-firestore-kmp = { module = "dev.gitlive:firebase-firestore", version.ref = "firebase-kmp"}

# KTOR
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

# KOIN
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }

# KOTLINX
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-play-services = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-date-time = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-dateTime" }
kotlinx-immutableCollections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-immutableCollections" }

# OKIO
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }

# NAVIGATION
navigation-compose = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }

# ROOM
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }

# SQLITE
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }

# TEST
androidx-testExt-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-testExt" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
firebaseCrashlitycs = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics" }
googleServices = { id = "com.google.gms.google-services", version.ref = "google-services" }
jetbrainsKotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "room" }
